# Path: src/db_updater/post_tasks/parallels/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for parallels"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

build_initial_map: Any
create_book_structure: Any
flatten_segment_map: Any
get_book_id: Any
invert_to_segment_structure: Any
parse_sutta_id: Any
sort_data_naturally: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    "build_initial_map",
    "create_book_structure",
    "flatten_segment_map",
    "get_book_id",
    "invert_to_segment_structure",
    "parse_sutta_id",
    "sort_data_naturally",
]